# Generated by Django 2.0.7 on 2018-07-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('distance', models.FloatField()),
                ('score', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.MiniGame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.User')),
            ],
        ),
    ]
